// AI server utilities.
//
// Wraps Cloudflare Workers AI (free tier, no API keys) with a graceful
// fallback to local smart-rule responses. Used by the AI Assistant and
// AI Search when users opt in to the LLM upgrade path.
//
// Cloudflare AI binding is declared in wrangler.toml:
//   [[ai]]
//   binding = "AI"
//
// In local dev (no Cloudflare env), `env.AI` is undefined and we fall
// back to null — callers should then use their own rules engine.

import type { Language } from "../components/AIAssistant";

export type ChatRole = "system" | "user" | "assistant";

export interface ChatMessage {
  role: ChatRole;
  content: string;
}

export interface AskAIOptions {
  /** System prompt that grounds the LLM in barangay context. */
  systemPrompt?: string;
  /** Conversation history. The last item is usually the new user message. */
  messages: ChatMessage[];
  /** Cap output tokens. Defaults to 384 to keep responses snappy. */
  maxTokens?: number;
  /** Sampling temperature. 0.4 keeps the assistant focused. */
  temperature?: number;
  /** Locale for the system prompt / response style. */
  lang?: Language;
}

export interface AskAIResult {
  /** LLM-generated reply. */
  text: string;
  /** True when generated by Cloudflare Workers AI. False on fallback / error. */
  usedLLM: boolean;
  /** Model id used (e.g. "@cf/meta/llama-3.1-8b-instruct"). */
  model?: string;
  /** Latency in milliseconds. */
  latencyMs: number;
  /** Error message if the LLM call failed. */
  error?: string;
}

// Default model — fast + multilingual (English / Filipino / Tagalog).
// Cloudflare's free tier allows ~10k neurons/day across all models.
const DEFAULT_MODEL = "@cf/meta/llama-3.1-8b-instruct";

const DEFAULT_SYSTEM = (lang: Language = "en") => {
  const base =
    "You are Cagri, the official AI assistant of Barangay Cagraray (Bato, Catanduanes, Philippines). " +
    "You help residents with barangay services, documents, disaster alerts, weather, officials, and community information. " +
    "Keep replies short (3–6 sentences), friendly, and accurate. When unsure, direct the user to the barangay hall or hotline 0917-XXX-XXXX. " +
    "Never invent fees, dates, or official contacts — say you don't know and offer to connect them with staff.";
  if (lang === "fil") {
    return base.replace(
      "Keep replies short (3–6 sentences), friendly, and accurate.",
      "Panatilihing maikli (3–6 pangungusap), magalang, at tumpak ang sagot.",
    );
  }
  if (lang === "bik") {
    return base.replace(
      "Keep replies short (3–6 sentences), friendly, and accurate.",
      "Panatilihing halipot (3–6 pangungusap), marahay, asin tama an mga tubag.",
    );
  }
  return base;
};

interface CloudflareAIEnv {
  AI?: {
    run: (
      model: string,
      input: {
        messages: ChatMessage[];
        max_tokens?: number;
        temperature?: number;
      },
    ) => Promise<{ response?: string }>;
  };
}

/**
 * Best-effort getter for the Cloudflare AI binding. Returns undefined
 * outside Cloudflare (local dev, plain Node, etc.) so the caller can
 * fall back to the smart-rule engine.
 */
function getAIBinding(): CloudflareAIEnv["AI"] | undefined {
  try {
    // Cloudflare Workers puts bindings on globalThis.
    const env = (globalThis as { AI?: CloudflareAIEnv["AI"] }).AI;
    if (env && typeof env.run === "function") return env;
  } catch {
    // ignore
  }
  return undefined;
}

/**
 * Call Cloudflare Workers AI with a graceful fallback. On any failure
 * (no binding, timeout, rate limit) returns usedLLM:false with a short
 * explanation so the caller can fall back to rules.
 */
export async function askAI(opts: AskAIOptions): Promise<AskAIResult> {
  const started = performance.now();
  const ai = getAIBinding();
  if (!ai) {
    return {
      text: "",
      usedLLM: false,
      latencyMs: 0,
      error: "AI binding unavailable (running outside Cloudflare Workers).",
    };
  }

  const system = opts.systemPrompt ?? DEFAULT_SYSTEM(opts.lang ?? "en");
  const messages: ChatMessage[] = [
    { role: "system", content: system },
    ...opts.messages,
  ];

  try {
    const res = await ai.run(DEFAULT_MODEL, {
      messages,
      max_tokens: opts.maxTokens ?? 384,
      temperature: opts.temperature ?? 0.4,
    });
    const text = (res?.response ?? "").trim();
    return {
      text,
      usedLLM: text.length > 0,
      model: DEFAULT_MODEL,
      latencyMs: Math.round(performance.now() - started),
    };
  } catch (err: any) {
    return {
      text: "",
      usedLLM: false,
      latencyMs: Math.round(performance.now() - started),
      error: err?.message ?? "AI call failed",
    };
  }
}

/** Quick health check — true if the AI binding is reachable. */
export async function isAIAvailable(): Promise<boolean> {
  return getAIBinding() !== undefined;
}
