app = "ecagraray-app"
primary_region = "sin"

kill_signal = "SIGINT"
kill_timeout = 5

[build]

[env]
  PORT = "4173"
  NODE_ENV = "production"

[mounts]
  source = "ecagraray_data"
  destination = "/app/data"

[http_service]
  internal_port = 4173
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
