import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState, useRef, useCallback } from "react";
import { uid, canRole, useSyncable } from "../lib/store";
import { Button, Card, EmptyState, Input, Modal, PageHeader, Badge, Select, Textarea } from "../components/ui-kit";
import { AlertTriangle, Plus, Trash2, Search, X, MapPin, RefreshCw, Cloud, CloudRain, CloudLightning, Wind, Thermometer, Droplets, Radio, Send, ChevronDown, ChevronUp, Bell, Eye, EyeOff, Siren, Home } from "lucide-react";
import { useAuth } from "../lib/auth";
import { pushNotification } from "../lib/notify";
import { toast } from "sonner";
import { DeleteModal } from "../components/delete-modal";
import { checkWeatherAndAutoAlert, describeWeather, getStoredWeatherData, setStoredWeatherData, type WeatherData, type AutoAlertResult } from "../lib/weather-alert";

export const Route = createFileRoute("/dashboard/alerts")({ component: Page });

const TYPES = ["Typhoon", "Flood", "Landslide", "Fire", "Earthquake", "Emergency", "Thunderstorm", "Heat Wave"];
const LEVELS = ["Low", "Moderate", "High", "Critical"];

interface A { id: string; type: string; level: string; title: string; description: string; location: string; status: "active" | "resolved"; createdAt: string; resolvedAt?: string; autoGenerated?: boolean; evacSuggested?: boolean }

const levelColor: Record<string, string> = {
  Low: "border-l-info bg-info/5",
  Moderate: "border-l-warning bg-warning/5",
  High: "border-l-destructive bg-destructive/5",
  Critical: "border-l-destructive bg-destructive/10",
};

function Page() {
  const { user } = useAuth();
  const canManage = canRole(user?.role, "alerts");
  const [items, setItems, updateItemsAndSync, refreshFromServer] = useSyncable<A[]>("alerts", [], { refreshInterval: 30000 });
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<A | null>(null);
  const [q, setQ] = useState("");
  const [deleteTarget, setDeleteTarget] = useState<A | null>(null);
  const [showWeather, setShowWeather] = useState(true);
  const [weather, setWeather] = useState<WeatherData | null>(getStoredWeatherData());
  const [autoEnabled, setAutoEnabled] = useState(() => localStorage.getItem("ecagraray:auto_alert") !== "off");
  const [dispatchPanel, setDispatchPanel] = useState(false);
  const [dispatchTarget, setDispatchTarget] = useState<A | null>(null);
  const [dispatchSent, setDispatchSent] = useState<Set<string>>(new Set());
  const [autoHistory, setAutoHistory] = useState<AutoAlertResult[]>([]);
  const [showAutoLog, setShowAutoLog] = useState(false);
  const [weatherLoading, setWeatherLoading] = useState(false);
  const [mobileFilterOpen, setMobileFilterOpen] = useState(false);

  const active = items.filter((a) => a.status === "active");
  const history = items.filter((a) => a.status === "resolved");

  useEffect(() => { refreshFromServer(); }, []);

  const checkWeather = useCallback(async () => {
    setWeatherLoading(true);
    try {
      const res = await fetch("https://api.open-meteo.com/v1/forecast?latitude=13.6094&longitude=124.3111&current=temperature_2m,apparent_temperature,weather_code,relative_humidity_2m,wind_speed_10m,precipitation&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,wind_speed_10m_max&timezone=Asia%2FManila&forecast_days=3");
      if (res.ok) {
        const data = (await res.json()) as WeatherData;
        setWeather(data);
        setStoredWeatherData(data);
      }
    } catch {} finally {
      setWeatherLoading(false);
    }
  }, []);

  useEffect(() => { checkWeather(); }, []);

  useEffect(() => {
    if (!autoEnabled) return;
    checkWeatherAndAutoAlert().then((r) => {
      if (r.generated) {
        setAutoHistory((prev) => [r, ...prev].slice(0, 10));
        const newAlerts = r.triggers.map((t) => ({
          id: uid(),
          type: t.type,
          level: t.level,
          title: t.title,
          description: `Auto-generated weather alert. ${t.title}. Take necessary precautions.`,
          location: "Cagraray, Bacacay, Albay",
          status: "active" as const,
          createdAt: new Date().toISOString(),
          autoGenerated: true,
          evacSuggested: t.level === "Critical" || t.level === "High",
        }));
        setItems((prev) => {
          const updated = [...newAlerts, ...prev];
          void updateItemsAndSync(updated);
          return updated;
        });
        toast.success(`${r.triggers.length} auto-alert(s) generated from weather data`);
      }
    }).catch(() => {});
  }, [autoEnabled]);

  const save = (e: React.FormEvent) => {
    e.preventDefault();
    if (!editing || !editing.title) return toast.error("Title required");
    const isNew = !editing.id;
    const payload = isNew ? { ...editing, id: uid(), createdAt: new Date().toISOString(), status: "active" as const } : editing;
    const nextItems = isNew ? [payload, ...items] : items.map((i) => i.id === payload.id ? payload : i);
    void updateItemsAndSync(nextItems);
    if (isNew) {
      pushNotification({ title: `${payload.level} ${payload.type} Alert`, message: payload.title, type: "alert" });
      if (payload.level === "Critical" || payload.level === "High") {
        toast.info("Evacuation centers notified — consider opening centers near " + (payload.location || "affected areas"));
      }
    }
    setOpen(false); toast.success("Saved");
  };

  const resolve = (a: A) => {
    void updateItemsAndSync(items.map((x) => x.id === a.id ? { ...x, status: "resolved" as const, resolvedAt: new Date().toISOString() } : x));
    toast.success("Alert resolved");
  };

  const remove = () => {
    if (!deleteTarget) return;
    void updateItemsAndSync(items.filter((x) => x.id !== deleteTarget.id));
    setDeleteTarget(null); toast.success("Deleted");
  };

  const handleDispatch = async () => {
    if (!dispatchTarget) return;
    const a = dispatchTarget;
    setDispatchSent((prev) => new Set(prev).add(a.id));
    pushNotification({
      title: a.level + " " + a.type + " - Action Required",
      message: a.title + " - " + (a.description || "Immediate attention needed.") + " | Location: " + (a.location || "Cagraray"),
      type: "alert",
    });
    toast.success(`Alert dispatched to all users and notification channels`);
    setDispatchPanel(false);
    setDispatchTarget(null);
  };

  const toggleAuto = () => {
    const next = !autoEnabled;
    setAutoEnabled(next);
    localStorage.setItem("ecagraray:auto_alert", next ? "on" : "off");
    toast.success(next ? "Auto-alert monitoring enabled" : "Auto-alert monitoring disabled");
  };

  const getSeverityIcon = (level: string) => {
    if (level === "Critical") return Siren;
    if (level === "High") return CloudLightning;
    if (level === "Moderate") return CloudRain;
    return Cloud;
  };

  const filteredActive = q.trim() ? active.filter((a) =>
    a.title.toLowerCase().includes(q.toLowerCase()) ||
    a.type.toLowerCase().includes(q.toLowerCase()) ||
    a.location?.toLowerCase().includes(q.toLowerCase())
  ) : active;
  const filteredHistory = q.trim() ? history.filter((a) =>
    a.title.toLowerCase().includes(q.toLowerCase()) ||
    a.type.toLowerCase().includes(q.toLowerCase())
  ) : history;

  const weatherCond = weather ? describeWeather(weather.current.weather_code) : null;

  if (!user || (user.role !== "super_admin" && user.role !== "captain" && user.role !== "disaster" && user.role !== "resident")) {
    return <Card><EmptyState icon={AlertTriangle} title="Access Restricted" description="You do not have permission to access Disaster Alerts." /></Card>;
  }

  return (
    <div className="max-w-full overflow-x-hidden">
      <PageHeader title="Disaster Alerts" subtitle="Emergency operations center with real-time weather monitoring and auto-dispatch." action={
        canManage ? (
          <div className="flex flex-wrap gap-2">
            <Button variant="outline" onClick={toggleAuto} className={autoEnabled ? "ring-2 ring-success/30" : ""}>
              <Radio className={`h-4 w-4 ${autoEnabled ? "text-success" : ""}`} />
              {autoEnabled ? "Auto On" : "Auto Off"}
            </Button>
            <Button onClick={() => { setEditing({ id: "", type: "Typhoon", level: "Moderate", title: "", description: "", location: "", status: "active", createdAt: "" }); setOpen(true); }}>
              <Plus className="h-4 w-4" /> New Alert
            </Button>
          </div>
        ) : undefined
      } />

      {/* Weather Panel */}
      <button onClick={() => setShowWeather(!showWeather)}
        className="w-full mb-4 flex items-center justify-between rounded-xl border border-border/40 bg-card p-3 sm:p-4 hover:bg-accent/5 transition"
      >
        <div className="flex items-center gap-2 sm:gap-3">
          <Cloud className="h-5 w-5 text-primary" />
          <span className="text-xs sm:text-sm font-bold uppercase tracking-wider">Real-Time Weather Monitor</span>
          {weatherLoading && <RefreshCw className="h-3.5 w-3.5 animate-spin text-muted-foreground" />}
          {autoEnabled && <Badge tone="success"><Radio className="h-3 w-3 mr-1" />Auto-Alert Active</Badge>}
        </div>
        {showWeather ? <ChevronUp className="h-4 w-4 text-muted-foreground" /> : <ChevronDown className="h-4 w-4 text-muted-foreground" />}
      </button>

      {showWeather && (
        <div className="mb-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
          <div className="rounded-xl border border-border/40 bg-card/60 p-3 sm:p-4">
            <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground mb-2">
              <Cloud className="h-3.5 w-3.5" /> Current
            </div>
            {weather ? (
              <>
                <div className="flex items-center gap-2">
                  <span className="text-xl sm:text-2xl font-black">{weather.current.temperature_2m}°C</span>
                  <span className="text-xs text-muted-foreground">feels {weather.current.apparent_temperature}°C</span>
                </div>
                <div className="flex items-center gap-1 mt-1 text-xs font-semibold">
                  <span style={{ color: weatherCond?.tone }}>{weatherCond?.label || "..."}</span>
                </div>
              </>
            ) : (
              <div className="text-xs text-muted-foreground">Loading...</div>
            )}
            <button onClick={checkWeather} disabled={weatherLoading}
              className="mt-2 flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider text-primary hover:text-primary/80 transition disabled:opacity-50"
            >
              <RefreshCw className={`h-3 w-3 ${weatherLoading ? "animate-spin" : ""}`} /> Refresh
            </button>
          </div>

          <div className="rounded-xl border border-border/40 bg-card/60 p-3 sm:p-4">
            <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground mb-2">
              <Thermometer className="h-3.5 w-3.5" /> Conditions
            </div>
            {weather ? (
              <div className="space-y-1.5">
                <div className="flex justify-between text-xs"><span>Humidity</span><span className="font-bold">{weather.current.relative_humidity_2m}%</span></div>
                <div className="flex justify-between text-xs"><span>Wind</span><span className="font-bold">{weather.current.wind_speed_10m} km/h</span></div>
                <div className="flex justify-between text-xs"><span>Precipitation</span><span className="font-bold">{weather.current.precipitation ?? 0} mm</span></div>
              </div>
            ) : <div className="text-xs text-muted-foreground">—</div>}
          </div>

          <div className="rounded-xl border border-border/40 bg-card/60 p-3 sm:p-4">
            <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground mb-2">
              <Radio className="h-3.5 w-3.5" /> Auto-Alert
            </div>
            <div className="flex items-center gap-2">
              <span className={`text-xs font-bold ${autoEnabled ? "text-success" : "text-muted-foreground"}`}>
                {autoEnabled ? "Monitoring Active" : "Disabled"}
              </span>
              <button onClick={toggleAuto} className={`rounded-full p-1.5 transition ${autoEnabled ? "bg-success/20 text-success" : "bg-muted text-muted-foreground"}`}>
                {autoEnabled ? <Eye className="h-3.5 w-3.5" /> : <EyeOff className="h-3.5 w-3.5" />}
              </button>
            </div>
            <div className="mt-1 text-[10px] text-muted-foreground">
              {autoEnabled ? "Weather checked every 5 min. Alerts auto-generated on thresholds." : "Click eye icon to enable auto-monitoring."}
            </div>
          </div>

          <div className="rounded-xl border border-border/40 bg-card/60 p-3 sm:p-4">
            <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground mb-2">
              <AlertTriangle className="h-3.5 w-3.5" /> Thresholds
            </div>
            <div className="space-y-1 text-[10px]">
              <div className="flex justify-between"><span>Rain ≥10mm/h</span><span className={`font-bold ${(weather?.current.precipitation ?? 0) >= 10 ? "text-destructive" : "text-success"}`}>{(weather?.current.precipitation ?? 0) >= 10 ? "Triggered" : "Normal"}</span></div>
              <div className="flex justify-between"><span>Wind ≥40km/h</span><span className={`font-bold ${(weather?.current.wind_speed_10m ?? 0) >= 40 ? "text-destructive" : "text-success"}`}>{(weather?.current.wind_speed_10m ?? 0) >= 40 ? "Triggered" : "Normal"}</span></div>
              <div className="flex justify-between"><span>Temp ≥38°C</span><span className={`font-bold ${(weather?.current.temperature_2m ?? 0) >= 38 ? "text-destructive" : "text-success"}`}>{(weather?.current.temperature_2m ?? 0) >= 38 ? "Triggered" : "Normal"}</span></div>
            </div>
          </div>

          {/* Auto-Alert History Log */}
          {autoHistory.length > 0 && (
            <div className="sm:col-span-2 lg:col-span-4">
              <button onClick={() => setShowAutoLog(!showAutoLog)}
                className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground hover:text-foreground transition"
              >
                <Bell className="h-3 w-3" /> Auto-Alert History ({autoHistory.length}) {showAutoLog ? <ChevronUp className="h-3 w-3" /> : <ChevronDown className="h-3 w-3" />}
              </button>
              {showAutoLog && (
                <div className="mt-2 rounded-lg border border-border/40 bg-muted/30 p-2 max-h-32 overflow-y-auto">
                  {autoHistory.map((h, idx) => (
                    <div key={idx} className="flex items-center gap-2 py-1 text-[10px] border-b border-border/20 last:border-0">
                      <Badge tone={h.triggers[0]?.level === "Critical" ? "danger" : h.triggers[0]?.level === "High" ? "warning" : "info"}>{h.triggers.length} alert(s)</Badge>
                      <span className="text-muted-foreground">{new Date(h.weather?.current ? Date.now() : 0).toLocaleTimeString()}</span>
                      <span className="truncate">{h.triggers.map((t) => t.title).join(", ")}</span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}
        </div>
      )}

      {/* Search & Filter */}
      <div className="mb-4 flex flex-col sm:flex-row gap-3">
        <div className="relative flex-1 max-w-sm">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Search alerts..." className="w-full rounded-2xl border border-border/60 bg-background/40 py-2.5 pl-10 pr-9 text-xs font-semibold outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10 min-h-[44px]" />
          {q && <button onClick={() => setQ("")} className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"><X className="h-4 w-4" /></button>}
        </div>
        <div className="flex items-center gap-2 text-xs font-semibold text-muted-foreground">
          <span className="flex items-center gap-1"><span className="h-2 w-2 rounded-full bg-destructive" /> {active.length} active</span>
          <span className="flex items-center gap-1"><span className="h-2 w-2 rounded-full bg-muted-foreground/40" /> {history.length} resolved</span>
        </div>
      </div>

      {/* Summary Stats */}
      <div className="grid gap-2 sm:gap-3 mb-4 sm:mb-6 grid-cols-2 sm:grid-cols-4">
        {LEVELS.map((l) => {
          const count = active.filter((a) => a.level === l).length;
          const Icon = getSeverityIcon(l);
          return (
            <div key={l} className={`rounded-xl border-l-4 bg-card p-3 sm:p-4 ${levelColor[l] || ""} ${l === "Critical" && count > 0 ? "ring-2 ring-destructive/20" : ""}`}>
              <div className="flex items-center gap-1.5">
                <Icon className="h-3 w-3 text-muted-foreground" />
                <span className="text-[9px] sm:text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{l}</span>
              </div>
              <div className={`mt-1 text-xl sm:text-2xl font-black ${count > 0 && l === "Critical" ? "text-destructive" : ""}`}>{count}</div>
            </div>
          );
        })}
      </div>

      {/* Active Alerts */}
      <Card>
        <h2 className="mb-3 font-semibold text-sm">Active Alerts</h2>
        {filteredActive.length === 0 ? (
          <EmptyState icon={AlertTriangle} title="No active alerts" description="All clear. Create an alert if a hazard occurs." />
        ) : (
          <div className="grid gap-3 sm:grid-cols-2">
            {filteredActive.map((a) => {
              const SevIcon = getSeverityIcon(a.level);
              return (
                <div key={a.id} className={`relative rounded-xl border-l-4 p-3 sm:p-4 ${levelColor[a.level] || "border-l-primary bg-primary/5"} ${a.autoGenerated ? "ring-1 ring-primary/20" : ""}`}>
                  {a.autoGenerated && (
                    <span className="absolute top-2 right-2 text-[8px] font-bold uppercase tracking-widest text-primary bg-primary/10 px-1.5 py-0.5 rounded">Auto</span>
                  )}
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex items-center gap-1.5 flex-wrap">
                      <Badge tone="danger" className="text-[9px]">{a.type}</Badge>
                      <Badge tone={a.level === "Critical" ? "danger" : a.level === "High" ? "warning" : a.level === "Moderate" ? "info" : "success"} className="text-[9px]">{a.level}</Badge>
                    </div>
                    <span className="text-[9px] sm:text-[10px] text-muted-foreground shrink-0">{new Date(a.createdAt).toLocaleDateString("en-PH", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })}</span>
                  </div>
                  <div className="mt-2 flex items-center gap-1.5">
                    <SevIcon className={`h-4 w-4 ${a.level === "Critical" ? "text-destructive" : "text-muted-foreground"}`} />
                    <span className="font-semibold text-sm">{a.title}</span>
                  </div>
                  {a.description && <p className="mt-1 text-xs text-muted-foreground line-clamp-2">{a.description}</p>}
                  <div className="mt-1.5 flex items-center gap-1 text-[10px] text-muted-foreground"><MapPin className="h-3 w-3" /> {a.location || "Cagraray, Bacacay, Albay"}</div>

                  {a.evacSuggested && (
                    <div className="mt-2 flex items-center gap-1.5 bg-warning/10 text-warning text-[10px] font-bold px-2 py-1 rounded-lg">
                      <Home className="h-3 w-3" /> Evacuation centers advised
                    </div>
                  )}

                  {canManage && (
                    <div className="mt-3 flex flex-wrap gap-1.5">
                      <Button variant="outline" onClick={() => resolve(a)} className="text-[10px] py-1.5 px-2 min-h-[32px]">Mark Resolved</Button>
                      <Button variant="outline" onClick={() => { setDispatchTarget(a); setDispatchPanel(true); }} className="text-[10px] py-1.5 px-2 min-h-[32px]">
                        <Send className="h-3 w-3" /> Dispatch
                      </Button>
                      {dispatchSent.has(a.id) && <span className="text-[9px] text-success self-center">Dispatched</span>}
                      <Button variant="ghost" onClick={() => setDeleteTarget(a)} className="text-[10px] py-1.5 px-2 min-h-[32px]"><Trash2 className="h-3.5 w-3.5" /></Button>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </Card>

      {/* Alert History */}
      <div className="mt-4 sm:mt-6">
        <Card>
          <h2 className="mb-3 font-semibold text-sm">Alert History</h2>
          {filteredHistory.length === 0 ? (
            <div className="py-6 text-center text-xs sm:text-sm text-muted-foreground">No past alerts</div>
          ) : (
            <div className="divide-y max-h-80 overflow-y-auto">
              {filteredHistory.map((a) => (
                <div key={a.id} className="flex flex-col sm:flex-row sm:items-center justify-between py-2.5 sm:py-3 gap-2 sm:gap-3">
                  <div className="min-w-0 flex-1">
                    <div className="font-medium text-xs sm:text-sm truncate">{a.title}</div>
                    <div className="text-[10px] sm:text-xs text-muted-foreground mt-0.5">
                      {a.type} · {a.level} · {new Date(a.createdAt).toLocaleDateString("en-PH", { month: "short", day: "numeric", year: "numeric" })}
                      {a.autoGenerated && <span className="ml-2 text-primary font-bold">Auto-generated</span>}
                    </div>
                    {a.location && <div className="text-[10px] text-muted-foreground mt-0.5 flex items-center gap-1"><MapPin className="h-3 w-3" /> {a.location}</div>}
                  </div>
                  <div className="flex items-center gap-2 shrink-0 self-start sm:self-center">
                    {a.resolvedAt && <span className="text-[9px] sm:text-[10px] text-muted-foreground">{new Date(a.resolvedAt).toLocaleDateString()}</span>}
                    <Badge tone="success" className="text-[9px]">Resolved</Badge>
                  </div>
                </div>
              ))}
            </div>
          )}
        </Card>
      </div>

      {/* Create Alert Modal */}
      <Modal open={open} onClose={() => setOpen(false)} title="New Alert">
        {editing && (
          <form onSubmit={save} className="space-y-3">
            <div className="grid grid-cols-2 gap-3">
              <Select label="Type" value={editing.type} onChange={(e) => setEditing({ ...editing, type: e.target.value })}>
                {TYPES.map((t) => <option key={t}>{t}</option>)}
              </Select>
              <Select label="Level" value={editing.level} onChange={(e) => setEditing({ ...editing, level: e.target.value })}>
                {LEVELS.map((l) => <option key={l}>{l}</option>)}
              </Select>
            </div>
            <Input label="Title *" value={editing.title} onChange={(e) => setEditing({ ...editing, title: e.target.value })} />
            <Input label="Location" value={editing.location} onChange={(e) => setEditing({ ...editing, location: e.target.value })} placeholder="Cagraray, Bacacay, Albay" />
            <Textarea label="Description" rows={3} value={editing.description} onChange={(e) => setEditing({ ...editing, description: e.target.value })} />
            <div className="flex justify-end gap-2">
              <Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button>
              <Button type="submit">Publish Alert</Button>
            </div>
          </form>
        )}
      </Modal>

      {/* Dispatch Panel */}
      <Modal open={dispatchPanel} onClose={() => { setDispatchPanel(false); setDispatchTarget(null); }} title="Dispatch Alert">
        {dispatchTarget && (
          <div className="space-y-4">
            <div className="rounded-xl bg-muted/30 p-3 sm:p-4">
              <div className="flex items-center gap-2 mb-2">
                <Badge tone="danger">{dispatchTarget.level}</Badge>
                <span className="font-semibold text-sm">{dispatchTarget.title}</span>
              </div>
              <p className="text-xs text-muted-foreground">{dispatchTarget.description || "No description"}</p>
              <div className="mt-2 text-[10px] text-muted-foreground"><MapPin className="h-3 w-3 inline" /> {dispatchTarget.location || "Cagraray"}</div>
            </div>

            <div className="space-y-2">
              <div className="flex items-center gap-2 text-xs font-semibold">
                <Bell className="h-4 w-4 text-primary" /> Dispatch Channels
              </div>
              <div className="grid gap-2">
                <div className="flex items-center gap-3 rounded-lg border border-border/40 p-2.5">
                  <input type="checkbox" defaultChecked className="rounded border-border accent-primary h-4 w-4" />
                  <span className="text-xs">Push Notifications (all users)</span>
                </div>
                <div className="flex items-center gap-3 rounded-lg border border-border/40 p-2.5">
                  <input type="checkbox" defaultChecked className="rounded border-border accent-primary h-4 w-4" />
                  <span className="text-xs">SMS Dispatch (via outgoing queue)</span>
                </div>
                <div className="flex items-center gap-3 rounded-lg border border-border/40 p-2.5">
                  <input type="checkbox" defaultChecked className="rounded border-border accent-primary h-4 w-4" />
                  <span className="text-xs">Email Alert (admin + disaster team)</span>
                </div>
                <div className="flex items-center gap-3 rounded-lg border border-border/40 p-2.5">
                  <input type="checkbox" className="rounded border-border accent-primary h-4 w-4" />
                  <span className="text-xs">Evacuation Center Notice</span>
                </div>
              </div>
            </div>

            <div className="flex justify-end gap-2">
              <Button variant="outline" onClick={() => { setDispatchPanel(false); setDispatchTarget(null); }}>Cancel</Button>
              <Button onClick={handleDispatch}><Send className="h-4 w-4" /> Dispatch Now</Button>
            </div>
          </div>
        )}
      </Modal>

      <DeleteModal open={!!deleteTarget} onClose={() => setDeleteTarget(null)} onConfirm={remove} itemName={deleteTarget?.title} message="Delete this alert permanently?" />
    </div>
  );
}
